### PR TITLE
Delphi bug fix 0.2.0

### PR DESCRIPTION
**Pull request by forever-new**
Hi

I tried to implement the Delphi port in my application and found several issues.

1. logic around camel case bonus doesn't check for non-uppercaseable characters. e.g. numbers - 'a4' gets camel case bonus.
   I suspect this is an issue not only for Delphi variant.

2. Extra delphi index "pascal_index = 1" breaks score calculation in couple of places. I moved this to .dpr file. 
3. Internal static arrays for "Matches" are not initialized and the output Matches array (on my PC) is often full of memory garbage.
4. Wrong calculation of unmatched count.
5. Extra option "first_letter_count" was not working well for me, I set it back to 1 to align with other ports logic.  

I fixed all of the above, in this patch. Please review.

### CODE REVIEW

**Comment by tajmone** [comment]
Hi @forever-new, and thanks for your contribution.

> I fixed all of the above, in this patch. Please review.

I don't know Delphi/Pascal, so I'll take your word for it.

Before merging, I ask you if could you please squash all three commits into one, with a commit message summarizing the improvements — just to keep the history on `master` shorter and cleaner.

I'll then update the READM file of the Delphi port, mentioning your improvements to the algorithm.

Ideally, if you could also implement a test for the Delphi algorithm to compare results with the output of the original algorithms (C++), as described in Issue #17, it would be the best solution, this would be really useful in order to mark the algorithm as passing the test (again, not knowing Delphi I need help for this). 

I came up with The test suite idea recently, after having managed to capture the output of the original C++ and JS algorithms (with a give data-set and search criteria), and was able to validate a couple of other algorithms ports.

**Comment by forever-new** [comment]
Hi @tajmone. 

I added the test code and output file test_results.txt as a proof it was tested successfully. I'm glad I did because I found another bug while testing.

Also I think I removed most of the double byte related code added by j.visser. It never worked for me, it cased several bugs and it was out of line with the other ports.
So I effectively removed both of his amendments: extra delphi index "pascal_index = 1" and update for double byte chars. 

I don't think I can squash my commits without closing and restarting this pull request. I think you can squash them when you merge into your master branch.

Squash commit message can be this (or please edit as you wish): 
1. Added check for non-uppercaseable characters. e.g. numbers -  so 'a4' doesn't get camel case bonus.
2. Removed extra delphi index "pascal_index = 1" - it broke the score calculation in couple of places.
3. Removed update for double byte chars, it was causing wrong calculation of unmatched count and other issues.
4. Added initialization for internal static array so the output Matches array is not populated with memory garbage.
5. Set option "first_letter_count" to 1 to align with other ports.
6. added test algorithm.

Cheers.

**Comment by tajmone** [comment]
> I added the test code and output file `test_results.txt` as a proof it was tested successfully. I'm glad I did because I found another bug while testing.

That's great, thank you @forever-new!

> Also I think I removed most of the double byte related code added by j.visser. It never worked for me, it cased several bugs and it was out of line with the other ports.

j.visser did mention in his release text that he had adapted the algorithm to his own needs.

> I don't think I can squash my commits without closing and restarting this pull request. 

You can. All you have to do is keep this PR open, squash them locally and then force push the PR branch again. Since PRs are branch-based, you can always tweak them locally and push them forcibly again.

> I think you can squash them when you merge into your master branch.

I could, but this would probably also merge all the commits messages together, leaving an unclear commit message which doesn't explain what changes are introduced by the commit. I also fear that this might obscure your name as the committer.

Sorry for asking to squash and update the message, but since these four commits all pertain to a same changeset, it's better to pack them together into a single commit, explaining what it does with a clear message, so when we'll go through the repository history it's clear what's going on in each commit.

**Comment by tajmone** [comment]
@forever-new, if you need help squashing the PR commits and force pushing let me know. Or, if you prefer, I can just merge the PR as it is, squash the commits locally and force push master.

**Pull request closed without merging**
